import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Main } from '../components/Main'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Sneakers</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className={styles.header}>
                <h1 className={styles.title}>SNEAKERS</h1>
            </header>

            <main className={styles.main}>
                <Main />
            </main>

            <footer className={styles.footer}>

            </footer>
        </div>
    )
}

export default Home
